# Generated by Django 5.1.5 on 2025-01-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '1'), (3, '1'), (4, '1'), (5, '1')], null=True),
        ),
    ]
