services:
  django:
    build:
        context: ../
        dockerfile: docker/Dockerfile
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - postgres_db
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn afisha.wsgi:application --bind 0.0.0.0:8000 --log-level info"
    volumes:
      - ../:/usr/src/app
      - static_volumes:/usr/src/app/back_statik/
      - media_volume:/usr/src/app/back_media/

  postgres_db:
    image: postgres:14.3-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  postgres_data:
  static_volumes:
  media_volume:
